name: Code Coverage
on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/*
      - src/**
      - build.zig
      - build.zig.zon
jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: ⬇️ Checkout
      uses: actions/checkout@v4

    - name: (Z) Install Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: master

    - run: zig env

    - name: Install kcov
      run: |
        sudo apt update
        sudo apt install -y kcov
        kcov --version

    - name: ▶️ Run Tests with Code Coverage
      run: |
        zig build test -Dcoverage --summary all

    - name: ⏫ Upload Coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        directory: zig-out/coverage/kcov-merged
        fail_ci_if_error: true
        verbose: true
