name: Code Coverage
on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/*
      - src/**
      - build.zig
      - build.zig.zon
jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: ⬇️ Checkout
      uses: actions/checkout@v4

    - name: (Z) Install Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: master

    - run: zig env

    - name: Install kcov
      run: |
        sudo apt-get update
        sudo apt-get install -y binutils-dev libssl-dev libcurl4-openssl-dev libelf-dev libstdc++-12-dev zlib1g-dev libdw-dev libiberty-dev
        wget https://github.com/SimonKagstrom/kcov/releases/download/v42/kcov-amd64.tar.gz
        sudo tar xf kcov-amd64.tar.gz -C /
        kcov --version

    - name: ▶️ Run Tests with Code Coverage
      run: |
        zig build test -Dcoverage --summary all

    - name: ⏫ Upload Coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        directory: zig-out/coverage/kcov-merged
        fail_ci_if_error: true
        verbose: true
