name: Code Coverage
on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/*
      - src/**
      - build.zig
      - build.zig.zon
jobs:
  coverage:
    if: github.repository_owner == 'zigtools'
    runs-on: ubuntu-latest

    steps:
    - name: ⬇️ Checkout
      uses: actions/checkout@v4

    - name: (Z) Install Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: master

    - run: zig env

    - name: Install kcov
      run: |
        wget https://github.com/SimonKagstrom/kcov/releases/download/v42/kcov-amd64.tar.gz
        sudo tar xf kcov-amd64.tar.gz -C /

    - name: Run Tests with kcov
      run: |
        kcov --version
        zig build test -Dcoverage --summary all

    - name: Upload to Codecov
      uses: codecov/codecov-action@v5
      with:
        directory: zig-out/coverage/kcov-merged
        fail_ci_if_error: true
        verbose: true
