name: Regression Tests

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: ⬇️ Checkout
      uses: actions/checkout@v4

    - name: 📦 Cache
      uses: actions/cache@v3
      id: cache-deps
      with:
        path: |
          ~/.local/bin
          ~/.local/lib
          ~/zig
        key: ${{ runner.os }}-deps-${{ format('{0:yyyy-MM-W}', github.event.repository.pushed_at) }}

    - name: (Z) Install Zig
      if: steps.cache-deps.outputs.cache-hit != 'true'
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: master

    - name: ▶️ Run tests
      shell: bash
      run: zig build test
